import customtkinter as ctk
import joblib
from fpdf import FPDF
from datetime import datetime
import logging
import csv
import os

# 1. Setup Professional System Logging 🕵️‍♂️
logging.basicConfig(
    filename='system_activity.log', 
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logging.info("Application Started.")

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")

# --- Modern PDF Generation Function ---
def generate_medical_report(diagnosis_text, radius, texture, perimeter, area, smoothness, doctor_name="Dr. Anshul"):
    pdf_document = FPDF()
    pdf_document.add_page()
    
    # 🎨 Define Custom Colors (RGB format)
    dark_blue_header = (20, 30, 48)
    pure_white = (255, 255, 255)
    standard_black = (40, 40, 40)
    light_gray_table = (245, 247, 250)
    
    # 🏥 1. Top Header Bar
    pdf_document.set_fill_color(*dark_blue_header)
    pdf_document.rect(0, 0, 210, 35, 'F')
    
    pdf_document.set_font("Arial", 'B', 22)
    pdf_document.set_text_color(*pure_white)
    pdf_document.set_y(12)
    pdf_document.cell(0, 10, txt="HOSPITAL AI DIAGNOSTICS", ln=True, align='C')
    
    # ✍️ 2. Reset color for body text
    pdf_document.set_text_color(*standard_black)
    pdf_document.set_y(45)
    
    # 📅 3. Meta Data (Doctor & Date)
    pdf_document.set_font("Arial", 'B', 12)
    pdf_document.cell(100, 8, txt=f"Attending Doctor: {doctor_name}", ln=False)
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf_document.set_font("Arial", '', 11)
    pdf_document.cell(90, 8, txt=f"Date: {current_time}", ln=True, align='R')
    
    pdf_document.line(10, 55, 200, 55) # Sleek horizontal divider line!
    pdf_document.ln(10)
    
    # 📊 4. Section Title
    pdf_document.set_font("Arial", 'B', 14)
    pdf_document.cell(0, 10, txt="Diagnostic Input Parameters:", ln=True)
    pdf_document.ln(3)
    
    # 📋 5. Styled Data Table
    pdf_document.set_font("Arial", '', 12)
    pdf_document.set_fill_color(*light_gray_table)
    
    patient_metrics = [
        ("Radius Mean", str(radius)),
        ("Texture Mean", str(texture)),
        ("Perimeter Mean", str(perimeter)),
        ("Area Mean", str(area)),
        ("Smoothness Mean", str(smoothness))
    ]
    
    for metric_name, metric_value in patient_metrics:
        # border=1 creates the outline, fill=True applies the background color
        pdf_document.cell(80, 10, txt=f"  {metric_name}", border=1, fill=True)
        pdf_document.cell(110, 10, txt=f"  {metric_value}", border=1, ln=True)
        
    pdf_document.ln(15)
    
    # 🎯 6. Dynamic Colored Result Box!
    if diagnosis_text.lower() == 'malignant':
        diagnosis_box_color = (220, 53, 69)  # Alert Red 🔴
    else:
        diagnosis_box_color = (40, 167, 69)  # Success Green 🟢
        
    pdf_document.set_fill_color(*diagnosis_box_color)
    pdf_document.set_text_color(*pure_white)
    pdf_document.set_font("Arial", 'B', 16)
    
    pdf_document.cell(0, 20, txt=f"FINAL AI DIAGNOSIS: {diagnosis_text.upper()}", ln=True, align='C', fill=True)
    
    # 🖋️ 7. Professional Footer
    pdf_document.set_y(265)
    pdf_document.set_font("Arial", 'I', 9)
    pdf_document.set_text_color(150, 150, 150)
    pdf_document.cell(0, 10, txt="Disclaimer: This report is generated by an AI model and is for informational purposes only.", align='C')
    
    # 💾 Save it!
    pdf_document.output("Styled_Medical_Report.pdf")
    logging.info("Styled PDF Medical Report generated and downloaded by user.")

# --- Save to Patient History CSV (UPDATED WITH DOCTOR NAME) ---
def save_patient_data(doctor_name, radius, texture, perimeter, area, smoothness, diagnosis):
    file_path = 'patient_history.csv'
    file_exists = os.path.isfile(file_path)
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    with open(file_path, mode='a', newline='') as database_file:
        csv_writer = csv.writer(database_file)
        
        # Added 'Doctor Name' to the headers! 👨‍⚕️
        if not file_exists:
            csv_writer.writerow(['Timestamp', 'Doctor Name', 'Radius', 'Texture', 'Perimeter', 'Area', 'Smoothness', 'Diagnosis'])
            logging.info("Created new patient_history.csv database file.")
            
        # Write the actual patient data along with the doctor who entered it! 📝
        csv_writer.writerow([current_time, doctor_name, radius, texture, perimeter, area, smoothness, diagnosis])
        logging.info(f"New patient prediction saved to database by {doctor_name}.")

# --- Main Dashboard ---
def open_main_dashboard(login_window, current_user):
    login_window.destroy()
    logging.info(f"Main dashboard opened by user: {current_user}")
    
    dashboard = ctk.CTk()
    dashboard.geometry("500x650")
    # Personalized Title! ✨
    dashboard.title(f"Hospital AI - Welcome {current_user}")
    
    try:
        ai_model = joblib.load('ai_medical_model.pkl')
        model_status_text = "AI Model Loaded Successfully! 🟢"
        logging.info("AI Model (ai_medical_model.pkl) loaded successfully.")
    except FileNotFoundError:
        model_status_text = "Error: ai_medical_model.pkl not found! 🔴"
        logging.error("Failed to load AI model. File not found.")

    ctk.CTkLabel(master=dashboard, text=model_status_text, font=("Arial", 12)).pack(pady=10)
    ctk.CTkLabel(master=dashboard, text="Patient Diagnostic Data", font=("Arial", 20, "bold")).pack(pady=10)
    
    radius_entry = ctk.CTkEntry(master=dashboard, placeholder_text="Radius Mean (e.g., 17.99)", width=250)
    radius_entry.pack(pady=5)
    
    texture_entry = ctk.CTkEntry(master=dashboard, placeholder_text="Texture Mean (e.g., 10.38)", width=250)
    texture_entry.pack(pady=5)
    
    perimeter_entry = ctk.CTkEntry(master=dashboard, placeholder_text="Perimeter Mean (e.g., 122.8)", width=250)
    perimeter_entry.pack(pady=5)
    
    area_entry = ctk.CTkEntry(master=dashboard, placeholder_text="Area Mean (e.g., 1001.0)", width=250)
    area_entry.pack(pady=5)
    
    smoothness_entry = ctk.CTkEntry(master=dashboard, placeholder_text="Smoothness Mean (e.g., 0.118)", width=250)
    smoothness_entry.pack(pady=5)

    result_label = ctk.CTkLabel(master=dashboard, text="Prediction will appear here", font=("Arial", 16, "bold"))
    download_button = ctk.CTkButton(master=dashboard, text="📄 Download PDF Report", width=250, height=40, font=("Arial", 14, "bold"), fg_color="#28a745")
    
    def run_prediction():
        try:
            val_radius = float(radius_entry.get())
            val_texture = float(texture_entry.get())
            val_perimeter = float(perimeter_entry.get())
            val_area = float(area_entry.get())
            val_smoothness = float(smoothness_entry.get())
            
            logging.info(f"Running prediction with inputs: Rad:{val_radius}, Tex:{val_texture}, Perim:{val_perimeter}, Area:{val_area}, Smooth:{val_smoothness}")
            
            prediction = ai_model.predict([[val_radius, val_texture, val_perimeter, val_area, val_smoothness]])
            
            if prediction[0] == 1:
                final_diagnosis = "Malignant"
                result_label.configure(text="⚠️ Diagnosis: Malignant", text_color="#FF4C4C")
            else:
                final_diagnosis = "Benign"
                result_label.configure(text="✅ Diagnosis: Benign", text_color="#00CC66")
            
            # Pass the current_user (Doctor's name) to the save function! 🩺
            save_patient_data(current_user, val_radius, val_texture, val_perimeter, val_area, val_smoothness, final_diagnosis)
                
            download_button.pack(pady=10)
            download_button.configure(command=lambda: generate_medical_report(final_diagnosis, val_radius, val_texture, val_perimeter, val_area, val_smoothness))
            
        except ValueError:
            result_label.configure(text="❌ Please enter valid numbers in all fields!", text_color="orange")
            download_button.pack_forget()
            logging.warning("Prediction failed: User entered invalid/non-numeric data.")

    predict_button = ctk.CTkButton(master=dashboard, text="Run AI Analysis", width=250, height=40, font=("Arial", 14, "bold"), command=run_prediction)
    predict_button.pack(pady=20)
    result_label.pack(pady=10)
    
    dashboard.mainloop()

# --- Login Screen ---
def build_login_screen():
    login_window = ctk.CTk()
    login_window.geometry("400x500")
    login_window.title("Hospital AI - Secure Login")
    
    ctk.CTkLabel(master=login_window, text="AI Medical System", font=("Arial", 24, "bold")).pack(pady=50)
    
    username_input = ctk.CTkEntry(master=login_window, placeholder_text="Username (e.g. Dr. Smith)", width=250, height=40)
    username_input.pack(pady=10)
    
    password_input = ctk.CTkEntry(master=login_window, placeholder_text="Password", show="*", width=250, height=40)
    password_input.pack(pady=10)
    
    def handle_login():
        entered_username = username_input.get()
        # Fallback just in case they leave it blank! 🛑
        if entered_username.strip() == "":
            entered_username = "Unknown Doctor"
            
        logging.info(f"Login attempt by username: '{entered_username}'")
        open_main_dashboard(login_window, entered_username)
    
    login_button = ctk.CTkButton(master=login_window, text="SUBMIT", width=250, height=40, font=("Arial", 14, "bold"), command=handle_login)
    login_button.pack(pady=30)
    
    login_window.mainloop()

if __name__ == "__main__":
    build_login_screen()